app1/urls.py
from django.urls import path
from app1.views import *

app_name='madhu'

urlpatterns=[
    path('world/',world,name='world')
]

app2/urls.py
from django.urls import path
from app1.views import *

app_name='nature'

urlpatterns=[
    path('environment/', environment,name='environment'),
]

project19/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
    
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def world(request):
    return render(request,'world.html')



def environment(request):
    return render(request,'environment.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

templates/environment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>nature is beauty</h1>
        <h2>we are nature lovers naturelover </h2>
        <a href="{% url 'nature:environment' %}">love the nature for peace</a>
    </center>
</body>
</html>

templates/world.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>love the world</h1>
        <h2>love the world because of beautiful realations</h2>
        <a href="{% url 'madhu:world' %}">love the world </a>
    </center>
</body>
</html>